apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  annotations:
    build.appstudio.openshift.io/request: configure-pac
    image.redhat.com/generate: '{"visibility": "private"}'
  name: trustification-guac
  namespace: trusted-content-tenant
spec:
  application: trustification
  componentName: trustification-guac
  source:
    git:
      context: ./
      dockerfileUrl: dockerfiles/Dockerfile.guac-ubi
      revision: trustification-main
      url: https://github.com/trustification/guac.git
