apiVersion: appstudio.redhat.com/v1beta1
kind: IntegrationTestScenario
metadata:
  labels:
    test.appstudio.openshift.io/optional: "false"
  name: provisioning-backend-tekton-insights
  namespace: gbenhaim-tenant
spec:
  application: provisioning-backend
  params:
  - name: APP_NAME
    value: provisioning
  - name: COMPONENTS
    value: ""
  - name: COMPONENTS_W_RESOURCES
    value: ""
  - name: COMPONENT_NAME
    value: provisioning
  - name: IQE_PLUGINS
    value: provisioning
  - name: IQE_MARKER_EXPRESSION
    value: api and smoke
  - name: IQE_FILTER_EXPRESSION
    value: test_plugin_accessible
  - name: IQE_REQUIREMENTS
    value: ""
  - name: IQE_REQUIREMENTS_PRIORITY
    value: ""
  - name: IQE_TEST_IMPORTANCE
    value: ""
  - name: IQE_CJI_TIMEOUT
    value: 30m
  - name: IQE_ENV
    value: clowder_smoke
  - name: IQE_SELENIUM
    value: "false"
  resolverRef:
    params:
    - name: url
      value: https://github.com/RedHatInsights/bonfire-tekton.git
    - name: revision
      value: main
    - name: pathInRepo
      value: pipelines/basic.yaml
    resolver: git
