apiVersion: appstudio.redhat.com/v1beta1
kind: RemoteSecret
metadata:
  name: redhat-user-workloads-pull
  namespace: rh-managed-bifrost-tenant
spec:
  targets:
    - namespace: rh-managed-bifrost-tenant
  secret:
    name: redhat-user-workloads-pull
    type: kubernetes.io/dockerconfigjson
    linkedTo:
      - serviceAccount:
          reference:
            name: release-sa-centos-bootc
