apiVersion: appstudio.redhat.com/v1beta1
kind: IntegrationTestScenario
metadata:
  name: release-service-enterprise-contract
  namespace: rhtap-spi-tenant
spec:
  application: remotesecret
  contexts:
  - description: Application testing
    name: application
  resolverRef:
    params:
    - name: url
      value: https://github.com/redhat-appstudio/build-definitions
    - name: revision
      value: main
    - name: pathInRepo
      value: pipelines/enterprise-contract-redhat-no-hermetic.yaml
    resolver: git
