---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: crt-redhat-acm-tenant-release-service-pipeline-rolebinding-dev
  namespace: crt-redhat-acm-tenant
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: release-pipeline-resource-role
subjects:
  - kind: ServiceAccount
    name: release-service-account
    namespace: rh-managed-red-hat-acm-tenant
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: crt-redhat-acm-tenant-release-service-pipeline-rolebinding-managed
  namespace: rh-managed-red-hat-acm-tenant
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: release-pipeline-resource-role
subjects:
  - kind: ServiceAccount
    name: release-service-account
    namespace: rh-managed-red-hat-acm-tenant
