apiVersion: appstudio.redhat.com/v1alpha1
kind: ReleasePlan
metadata:
  name: osde2e-release-as-service
  namespace: osde2e-cicada-tenant
  labels:
    release.appstudio.openshift.io/auto-release: 'true'
    release.appstudio.openshift.io/standing-attribution: 'true'
spec:
  application: osde2e
  target: rhtap-releng-tenant
