apiVersion: appstudio.redhat.com/v1beta1
kind: RemoteSecret
metadata:
  name: pyxis-staging-secret-remote-secret
  namespace: rh-managed-rhtap-ser-tenant
spec:
  secret:
    name: pyxis-staging-secret
    type: Opaque
    linkedTo:
      - serviceAccount:
          reference:
            name: rhtap-servicerelease-sa
  targets:
    - namespace: rh-managed-rhtap-ser-tenant
---
apiVersion: appstudio.redhat.com/v1beta1
kind: RemoteSecret
metadata:
  name: pyxis-production-secret-remote-secret
  namespace: rh-managed-rhtap-ser-tenant
spec:
  secret:
    name: pyxis-production-secret
    type: Opaque
    linkedTo:
      - serviceAccount:
          reference:
            name: rhtap-servicerelease-sa
  targets:
    - namespace: rh-managed-rhtap-ser-tenant
