apiVersion: appstudio.redhat.com/v1beta1
kind: RemoteSecret
metadata:
  name: slack-webhook-notification-secret-remote-secret
  namespace: rh-managed-rhtap-ser-tenant
spec:
  secret:
    name: slack-webhook-notification-secret
    type: Opaque
    linkedTo:
      - serviceAccount:
          reference:
            name: rhtap-servicerelease-sa
  targets:
    - namespace: rh-managed-rhtap-ser-tenant
