apiVersion: appstudio.redhat.com/v1alpha1
kind: ReleasePlan
metadata:
  name: notifications-release-as-ms
  namespace: hcc-notifications-tenant
  labels:
    release.appstudio.openshift.io/auto-release: 'true'
    release.appstudio.openshift.io/standing-attribution: 'true'
spec:
  application: notifications
  target: rhtap-releng-tenant
  # Lowers the delay before the release CR garbage collector can delete release snapshots.
  releaseGracePeriodDays: 2
