apiVersion: appstudio.redhat.com/v1beta1
kind: IntegrationTestScenario
metadata:
  labels:
    test.appstudio.openshift.io/optional: "true"
  name: notifications-tekton-insights
  namespace: hcc-notifications-tenant
spec:
  application: notifications
  contexts:
  - description: Application testing
    name: application
  resolverRef:
    params:
    - name: url
      value: https://github.com/RedHatInsights/bonfire-tekton.git
    - name: revision
      value: main
    - name: pathInRepo
      value: pipelines/basic.yaml
    resolver: git
  params:
  - name: APP_NAME
    value: notifications
  - name: COMPONENT_NAME
    value: notifications-backend
  - name: COMPONENTS_W_RESOURCES
    value: historical-system-profiles system-baseline notifications-backend notifications-engine
  - name: IQE_PLUGINS
    value: notifications
  - name: IQE_MARKER_EXPRESSION
    value: notification_smoke and api
