---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Application
metadata:
  name: assisted-events-stream-saas-main
spec:
  displayName: assisted-events-stream-saas-main
---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: assisted-events-stream-saas-main
  annotations:
    build.appstudio.openshift.io/request: configure-pac
    image.redhat.com/generate: '{"visibility": "public"}'
spec:
  application: assisted-events-stream-saas-main
  componentName: assisted-events-stream-saas-main
  skipGitOpsResourceGeneration: true
  source:
    git:
      context: ./
      dockerfileUrl: Dockerfile
      revision: master
      url: https://github.com/openshift-assisted/assisted-events-stream.git
---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ReleasePlan
metadata:
  labels:
    release.appstudio.openshift.io/author: assisted-installer-team
    release.appstudio.openshift.io/auto-release: "true"
    release.appstudio.openshift.io/releasePlanAdmission: assisted-installer-saas
    release.appstudio.openshift.io/standing-attribution: "false"
  name: assisted-events-stream-saas-main
spec:
  application: assisted-events-stream-saas-main
  releaseGracePeriodDays: 7
  target: rhtap-releng-tenant
