apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - assisted-events-stream-saas-main.yaml
  - assisted-image-service-saas-main.yaml
  - assisted-service-saas-main.yaml
  - auto-report-saas-main.yaml
  - bug-master-bot-saas-main.yaml
  - jira-unfurl-bot-saas-main.yaml
  - prow-jobs-scraper-saas-main.yaml
