apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./content-sources-backend.yaml
  - ./provisioning-backend-integration.yaml
  - ./provisioning-frontend-integration.yaml
  - ../../../../lib/consoledot-test-pipeline
namespace: rh-hms-tenant
