apiVersion: appstudio.redhat.com/v1beta1
kind: RemoteSecret
metadata:
  name: github-pat-enriquebelarte-terraform-provider-rhcs
  namespace: rhtap-releng-tenant
spec:
  secret:
    name: github-pat-enriquebelarte-terraform-provider-rhcs-secret
    type: Opaque
    linkedTo:
      - serviceAccount:
          reference:
            name: release-github-terraform-dev
  targets:
    - namespace: rhtap-releng-tenant
