apiVersion: appstudio.redhat.com/v1beta1
kind: RemoteSecret
metadata:
  name: quay-token-redhat-prod-secret-remote-secret
  namespace: rhtap-releng-tenant
spec:
  secret:
    name: quay-token-redhat-prod-secret
    type: kubernetes.io/dockerconfigjson
    linkedTo:
      - serviceAccount:
          reference:
            name: release-registry-prod
  targets:
    - namespace: rhtap-releng-tenant
