apiVersion: appstudio.redhat.com/v1beta1
kind: RemoteSecret
metadata:
  name: redhat-user-workloads-pull
  namespace: rhtap-releng-tenant
spec:
  targets:
    - namespace: rhtap-releng-tenant
  secret:
    name: redhat-user-workloads-pull
    type: kubernetes.io/dockerconfigjson
    linkedTo:
      - serviceAccount:
          reference:
            name: konflux-ci-servicerelease-sa
      - serviceAccount:
          reference:
            name: konflux-integration-service-sa
      - serviceAccount:
          reference:
            name: konflux-servicerelease-sa
      - serviceAccount:
          reference:
            name: redhat-acm-service-account
      - serviceAccount:
          reference:
            name: redhat-acs-service-account
      - serviceAccount:
          reference:
            name: release-app-interface-prod
      - serviceAccount:
          reference:
            name: release-app-interface-staging
      - serviceAccount:
          reference:
            name: release-github-terraform-dev
      - serviceAccount:
          reference:
            name: release-github-terraform-prod
      - serviceAccount:
          reference:
            name: release-index-image-prod
      - serviceAccount:
          reference:
            name: release-index-image-staging
      - serviceAccount:
          reference:
            name: release-registry-dev
      - serviceAccount:
          reference:
            name: release-registry-prod
      - serviceAccount:
          reference:
            name: release-registry-staging
