apiVersion: appstudio.redhat.com/v1beta1
kind: RemoteSecret
metadata:
  name: pyxis-staging-secret-remote-secret
  namespace: rhtap-releng-tenant
spec:
  secret:
    name: pyxis-staging-secret
    type: Opaque
    linkedTo:
      - serviceAccount:
          reference:
            name: release-registry-staging
      - serviceAccount:
          reference:
            name: release-registry-dev
  targets:
    - namespace: rhtap-releng-tenant
