apiVersion: appstudio.redhat.com/v1alpha1
kind: ReleasePlan
metadata:
  labels:
    release.appstudio.openshift.io/auto-release: "false"
    release.appstudio.openshift.io/standing-attribution: "false"
  name: rh-acs-fast-stream
  namespace: rh-acs-tenant
spec:
  application: acs
  target: rhtap-releng-tenant
