apiVersion: appstudio.redhat.com/v1beta1
kind: RemoteSecret
metadata:
  name: fbc-publishing-credentials-remote-secret
  namespace: rh-managed-cnv-fbc-tenant
spec:
  secret:
    name: fbc-publishing-credentials
    type: Opaque
    linkedTo:
      - serviceAccount:
          reference:
            name: release-service-account
  targets:
    - namespace: rh-managed-cnv-fbc-tenant
