apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ec-policy.yaml
  - persistent_volume_claim.yaml
  - release_plan_admission.yaml
  - release-pipeline-sa.yaml
  - release-service-account-build-rb.yaml
  - fbc-publishing-credentials-remote-secret.yaml
namespace: rh-managed-cnv-fbc-tenant
