apiVersion: appstudio.redhat.com/v1alpha1
kind: ReleasePlanAdmission
metadata:
  name: fbc-release
  namespace: rh-managed-cnv-fbc-tenant
spec:
  application: cnv-fbc
  origin: cnv-fbc-tenant
  releaseStrategy: fbc-strategy
---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ReleasePlanAdmission
metadata:
  name: fbc-staged-index-release-v4-14
  namespace: rh-managed-cnv-fbc-tenant
spec:
  application: cnv-fbc-v4-14
  origin: cnv-fbc-tenant
  releaseStrategy: fbc-staged-index-strategy
---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ReleasePlanAdmission
metadata:
  name: fbc-staged-index-release-v4-13
  namespace: rh-managed-cnv-fbc-tenant
spec:
  application: cnv-fbc-v4-13
  origin: cnv-fbc-tenant
  releaseStrategy: fbc-staged-index-strategy
---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ReleasePlanAdmission
metadata:
  name: fbc-staged-index-release-v4-12
  namespace: rh-managed-cnv-fbc-tenant
spec:
  application: cnv-fbc-v4-12
  origin: cnv-fbc-tenant
  releaseStrategy: fbc-staged-index-strategy
---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ReleasePlanAdmission
metadata:
  name: fbc-staged-index-release-v4-11
  namespace: rh-managed-cnv-fbc-tenant
spec:
  application: cnv-fbc-v4-11
  origin: cnv-fbc-tenant
  releaseStrategy: fbc-staged-index-strategy
---
