apiVersion: appstudio.redhat.com/v1alpha1
kind: ReleasePlanAdmission
metadata:
  name: fbc-release-to-prod
  namespace: rh-managed-cnv-fbc-tenant
spec:
  applications:
    - cnv-fbc-v4-14
  data:
    fbc:
      fromIndex: 'quay.io/rh-osbs/iib-pub:v4.14'
      targetIndex: 'quay.io/redhat/redhat----redhat-operator-index:v4.14'
      binaryImage: 'registry.redhat.io/openshift4/ose-operator-registry:v4.14'
      fbcPublishingCredentials: 'fbc-production-publishing-credentials'  # cred to publish built index
      iibServiceConfigSecret: 'iib-services-config'  # depending upon environment
      iibOverwriteFromIndexCredential: 'iib-overwrite-fromimage-credentials'
      requestUpdateTimeout: 860
      buildTimeoutSeconds: 800
    sign:
      configMapName: hacbs-signing-pipeline-config-redhatrelease2
  pipelineRef:
    resolver: git
    params:
      - name: url
        value: "https://github.com/redhat-appstudio/release-service-catalog.git"
      - name: revision
        value: main
      - name: pathInRepo
        value: "pipelines/fbc-release/fbc-release.yaml"
  origin: cnv-fbc-tenant
  policy: rh-fbc-policy
  serviceAccount: release-service-account
