apiVersion: appstudio.redhat.com/v1beta2
kind: IntegrationTestScenario
metadata:
  name: ros-backend-enterprise-contract
  namespace: ros-tenant
spec:
  params: 
    - name: POLICY_CONFIGURATION
      value: rhtap-releng-tenant/app-interface-standard
  application: ros-backend
  contexts:
    - description: Application testing
      name: application
  resolverRef:
    params:
      - name: url
        value: 'https://github.com/konflux-ci/build-definitions'
      - name: revision
        value: main
      - name: pathInRepo
        value: pipelines/enterprise-contract.yaml
    resolver: git
