apiVersion: appstudio.redhat.com/v1beta1
kind: IntegrationTestScenario
metadata:
  labels:
    test.appstudio.openshift.io/optional: "true"
  name: export-service-tekton-insights
  namespace: hcc-pipeline-tenant
spec:
  application: export-service
  contexts:
  - description: Application testing
    name: application
  params:
  - name: APP_NAME
    value: export-service
  - name: BONFIRE_COMPONENT_NAME
    value: export-service
  - name: COMPONENT_NAME
    value: export-service
  - name: IQE_PLUGINS
    value: export-service
  - name: IQE_FILTER_EXPRESSION
    value: ""
  - name: IQE_CJI_TIMEOUT
    value: 30m
  - name: IQE_ENV
    value: clowder_smoke
  - name: IQE_ENV_VARS
    value: DYNACONF_USER_PROVIDER__rbac_enabled=false
  resolverRef:
    params:
    - name: url
      value: https://github.com/gbenhaim/tekton-insights.git
    - name: revision
      value: main
    - name: pathInRepo
      value: pipelines/basic.yaml
    resolver: git
