apiVersion: appstudio.redhat.com/v1alpha1
kind: ReleasePlan
metadata:
  labels:
    release.appstudio.openshift.io/auto-release: "true"
    release.appstudio.openshift.io/standing-attribution: "true"
  name: export-service-release-as-ms
  namespace: hcc-pipeline-tenant
spec:
  application: export-service
  target: rhtap-releng-tenant
