apiVersion: appstudio.redhat.com/v1alpha1
kind: ReleasePlanAdmission
metadata:
  labels:
    release.appstudio.openshift.io/auto-release: "true"
  name: rhtap-segment-bridge-rpa
  namespace: rh-managed-rhtap-ser-tenant
spec:
  application: segment-bridge
  displayName: ""
  origin: rhtap-o11y-tenant
  releaseStrategy: rhtap-service-push-strategy
