apiVersion: appstudio.redhat.com/v1alpha1
kind: ReleasePlanAdmission
metadata:
  labels:
    release.appstudio.openshift.io/auto-release: "true"
  name: rhtap-internal-services-rpa
  namespace: rh-managed-rhtap-ser-tenant
spec:
  applications:
  - internal-services
  data:
    images:
      addGitShaTag: true
      defaultTag: latest
    mapping:
      components:
      - name: internal-services
        repository: quay.io/redhat-appstudio/internal-services
    pyxis:
      secret: pyxis-staging-secret
      server: stage
    slack:
      slack-notification-secret: release-team-slack-webhook-notification-secret
      slack-webhook-notification-secret-keyname: internal-services
  origin: rhtap-release-2-tenant
  pipelineRef:
    params:
    - name: url
      value: https://github.com/scoheb/release-service-catalog.git
    - name: revision
      value: refactor-slack
    - name: pathInRepo
      value: pipelines/rhtap-service-push/rhtap-service-push.yaml
    resolver: git
  policy: rh-policy
  serviceAccount: rhtap-servicerelease-sa
