apiVersion: appstudio.redhat.com/v1alpha1
kind: ReleasePlanAdmission
metadata:
  labels:
    release.appstudio.openshift.io/auto-release: "true"
  name: rhtap-segment-bridge-rpa
  namespace: rh-managed-rhtap-ser-tenant
spec:
  applications:
  - segment-bridge
  data:
    images:
      addGitShaTag: true
      defaultTag: latest
    mapping:
      components:
      - name: segment-bridge
        repository: quay.io/redhat-appstudio/segment-bridge
    pyxis:
      secret: pyxis-production-secret
      server: production
  origin: rhtap-o11y-tenant
  pipeline:
    pipelineRef:
      params:
      - name: url
        value: https://github.com/redhat-appstudio/release-service-catalog.git
      - name: revision
        value: production
      - name: pathInRepo
        value: pipelines/rhtap-service-push/rhtap-service-push.yaml
      resolver: git
    serviceAccountName: rhtap-servicerelease-sa
  policy: rh-policy
