---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Application
metadata:
  name: hello-secret
  namespace: ergonzale-tenant
  annotations:
    # This stub annotation is needed until KFLUXBUGS-1300 is resolved.
    hello: world
spec:
  displayName: hello-secret
---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: hello-secret
  namespace: ergonzale-tenant
annotations:
  build.appstudio.openshift.io/request: configure-pac
spec:
  application: hello-secret
  componentName: hello-secret
  skipGitOpsResourceGeneration: true
  source:
    git:
      revision: main
      url: https://github.com/ernesgonzalez33/hello-secret
      dockerfileUrl: Dockerfile
      context: ./
---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  annotations:
    image-controller.appstudio.redhat.com/update-component-image: true
  name: hello-secret
  labels:
    appstudio.redhat.com/application: hello-secret
    appstudio.redhat.com/component: hello-secret 
spec:
  image:
    name: hello-secret/hello-secret
    visibility: public
