apiVersion: appstudio.redhat.com/v1alpha1
kind: Application
metadata:
  name: bootc-c9s
  namespace: centos-bootc-tenant
spec:
  displayName: bootc-c9s
---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  annotations:
    build.appstudio.openshift.io/request: configure-pac
    image.redhat.com/generate: '{"visibility": "public"}'
  name: bootc-image-builder-c9s
  namespace: centos-bootc-tenant
spec:
  application: bootc-c9s
  componentName: bootc-image-builder-c9s
  skipGitOpsResourceGeneration: true
  source:
    git:
      context: ./
      dockerfileUrl: Containerfile
      revision: main
      url: https://gitlab.com/redhat/rhel/bifrost/bootc-image-builder.git
---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  annotations:
    build.appstudio.openshift.io/request: configure-pac
    image.redhat.com/generate: '{"visibility": "public"}'
  name: centos-bootc-c9s
  namespace: centos-bootc-tenant
spec:
  application: bootc-c9s
  componentName: centos-bootc-c9s
  skipGitOpsResourceGeneration: true
  source:
    git:
      context: ./
      dockerfileUrl: Containerfile
      revision: main
      url: https://gitlab.com/redhat/centos-stream/containers/bootc.git
