apiVersion: appstudio.redhat.com/v1beta1
kind: RemoteSecret
metadata:
  name: pyxis-staging-secret-remote-secret
  namespace: managed-release-team-tenant
spec:
  secret:
    name: pyxis-staging-secret
    type: Opaque
  targets:
  - namespace: managed-release-team-tenant
