apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../lib/consoledot-test-pipeline
  - bonfire-tekton.yaml
  - release-plan.yaml
  - integration_test_scenario_consoledot_frontend.yaml
  - consoledot-frontend-standard-policy.yaml
  - insights-ingress-go-clowder-test.yaml
namespace: rhtap-migration-tenant
