apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  annotations:
    build.appstudio.openshift.io/request: configure-pac
    image.redhat.com/generate: '{"visibility": "public"}'
  name: bonfire-tekton
  namespace: rhtap-migration-tenant
spec:
  application: bonfire-tekton
  componentName: bonfire-tekton
  source:
    git:
      context: ./
      dockerfileUrl: Dockerfile
      revision: main
      url: https://github.com/RedHatInsights/bonfire-tekton.git
