apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  annotations:
    build.appstudio.openshift.io/request: configure-pac
    image.redhat.com/generate: '{"visibility": "public"}'
  name: tekton-insights
  namespace: rhtap-migration-tenant
spec:
  application: tekton-insights
  componentName: tekton-insights
  source:
    git:
      context: ./
      dockerfileUrl: Dockerfile
      revision: main
      url: https://github.com/RedHatInsights/bonfire-tekton.git
