apiVersion: appstudio.redhat.com/v1alpha1
kind: EnterpriseContractPolicy
metadata:
  name: consoledot-frontend-standard
  namespace: rhtap-migration-tenant
spec:
  configuration:
    exclude:
    - cve
    - base_image_registries.base_image_permitted
    - labels.disallowed_inherited_labels
    - tasks.required_tasks_found:source-build
    - test.no_skipped_tests:sast-snyk-check
    - hermetic_build_task.build_task_hermetic
    - attestation_task_bundle.tasks_defined_in_bundle
    - tasks.required_tasks_found:prefetch-dependencies
    - tasks.pinned_task_refs
    include:
    - '@redhat'
  description: Includes rules to set a standard for current App Interface deployments
  publicKey: k8s://openshift-pipelines/public-key
  sources:
  - data:
    - github.com/release-engineering/rhtap-ec-policy//data
    - oci::quay.io/redhat-appstudio-tekton-catalog/data-acceptable-bundles:latest
    name: Release Policies
    policy:
    - oci::quay.io/enterprise-contract/ec-release-policy:git-8f22774@sha256:f887fb71d95ebe45703917da60770580035e9158b26b89e56efbba05474f6ec2
