apiVersion: appstudio.redhat.com/v1beta1
kind: IntegrationTestScenario
metadata:
  name: serverless-workflows-enterprise-contract
  namespace: orchestrator-releng-tenant
spec:
  params: 
    - name: POLICY_CONFIGURATION
      value: rhtap-releng-tenant/registry-standard
  application: serverless-workflows 
  contexts:
    - description: Application testing
      name: application
  resolverRef:
    params:
      - name: url
        value: 'https://github.com/konflux-ci/build-definitions'
      - name: revision
        value: main
      - name: pathInRepo
        value: pipelines/enterprise-contract.yaml
    resolver: git
