apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - persistent_volume_claim.yaml
  - ec-policy.yaml
  - release-plan-admission
  - release_strategy.yaml
  - release-pipeline-sa.yaml
  - release-service-account-build-rb.yaml
  - remote-secrets
namespace: rh-managed-mng-s-2-tenant
