apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  annotations:
    build.appstudio.openshift.io/request: configure-pac
    image.redhat.com/generate: '{"visibility": "public"}'
  name: repository-validator
  namespace: konflux-infra-tenant
spec:
  application: repository-validator
  componentName: repository-validator
  source:
    git:
      context: ./
      dockerfileUrl: Dockerfile
      revision: main
      url: https://github.com/konflux-ci/repository-validator.git
