apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ccx-integ-test.yaml
  - ../../../../lib/consoledot-test-pipeline
  - provisioning-backend-test.yaml
namespace: gbenhaim-tenant
