apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  annotations:
    build.appstudio.openshift.io/pipeline: '{"name":"docker-build","bundle":"latest"}'
    build.appstudio.openshift.io/request: configure-pac
  name: gatekeeper-operator-bundle
  namespace: konflux-samples-tenant
spec:
  application: olm-operator
  componentName: gatekeeper-operator-bundle
  source:
    git:
      context: ./
      dockerfileUrl: Containerfile.gatekeeper-operator-bundle
      revision: main
      url: https://github.com/konflux-ci/olm-operator-konflux-sample
