apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: releng-gitops-repo-ro
  namespace: rhtap-releng-tenant
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: releng-gitops-repo-role-ro
subjects:
  - kind: ServiceAccount
    namespace: rhtap-releng-tenant
    name: releng-gitops-repo-ro
