apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: releng-gitops-repo-role-rw
  namespace: rhtap-releng-tenant
rules:
  - apiGroups:
      - appstudio.redhat.com
    resources:
      - releaseplanadmissions
      - releasestrategies
      - enterprisecontractpolicies
    verbs:
      - get
      - list
      - create
      - update
      - patch
      - delete
