apiVersion: appstudio.redhat.com/v1beta1
kind: RemoteSecret
metadata:
  name: rh-trex-tenant-quay-token-secret-remote-secret
spec:
  secret:
    name: rh-trex-tenant-quay-token-secret
    type: kubernetes.io/dockerconfigjson
    linkedTo:
      - serviceAccount:
          reference:
            name: rh-trex-tenant-release-service-account
  targets:
    - namespace: rh-managed-mng-s-2-tenant
