apiVersion: appstudio.redhat.com/v1alpha1
kind: EnterpriseContractPolicy
metadata:
  name: rh-policy
  namespace: rh-managed-red-hat-acm-tenant
spec:
  configuration:
    exclude:
    - step_image_registries
    include:
    - '@slsa3'
  description: Includes rules for levels 1, 2 & 3 of SLSA v0.1.
  publicKey: k8s://openshift-pipelines/public-key
  sources:
  - data:
    - github.com/release-engineering/rhtap-ec-policy//data
    - oci::quay.io/redhat-appstudio-tekton-catalog/data-acceptable-bundles:latest
    name: Default
    policy:
    - oci::quay.io/enterprise-contract/ec-release-policy:git-8f22774@sha256:f887fb71d95ebe45703917da60770580035e9158b26b89e56efbba05474f6ec2
