apiVersion: appstudio.redhat.com/v1alpha1
kind: ReleasePlanAdmission
metadata:
  name: hypershift-operator-rpa
  namespace: rh-managed-red-hat-acm-tenant
spec:
  applications:
  - hypershift-operator
  - hypershift-operator-main-hotfix
  data:
    images:
      addGitShaTag: true
      defaultTag: latest
    mapping:
      components:
      - name: hypershift-operator-main
        repository: quay.io/acm-d/rhtap-hypershift-operator
      - name: hypershift
        repository: quay.io/acm-d/rhtap-hypershift-operator
    pyxis:
      secret: pyxis-production-secret
      server: production
  origin: crt-redhat-acm-tenant
  pipeline:
    pipelineRef:
      params:
      - name: url
        value: https://github.com/konflux-ci/release-service-catalog.git
      - name: revision
        value: production
      - name: pathInRepo
        value: pipelines/push-to-external-registry/push-to-external-registry.yaml
      resolver: git
    serviceAccountName: release-service-account
  policy: rh-policy
