apiVersion: appstudio.redhat.com/v1alpha1
kind: ReleasePlanAdmission
metadata:
  name: hypershift-operator-rpa
  namespace: rh-managed-red-hat-acm-tenant
spec:
  applications:
  - hypershift-operator
  data:
    images:
      addGitShaTag: true
      defaultTag: latest
    mapping:
      components:
      - name: hypershift-operator-main
        repository: quay.io/acm-d/rhtap-hypershift-operator
    pyxis:
      secret: pyxis-staging-secret
      server: stage
  origin: crt-redhat-acm-tenant
  pipelineRef:
    params:
    - name: url
      value: https://github.com/redhat-appstudio/release-service-catalog.git
    - name: revision
      value: main
    - name: pathInRepo
      value: pipelines/push-to-external-registry/push-to-external-registry.yaml
    resolver: git
  policy: rh-policy
  serviceAccount: release-service-account
