annotations:
  build.appstudio.openshift.io/request: configure-pac
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: hello-secret
  namespace: ergonzale-tenant
spec:
  application: hello-secret
  componentName: hello-secret
  skipGitOpsResourceGeneration: true
  source:
    git:
      context: ./
      dockerfileUrl: Dockerfile
      revision: main
      url: https://github.com/ernesgonzalez33/hello-secret
