apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  annotations:
    image-controller.appstudio.redhat.com/update-component-image: "true"
  labels:
    appstudio.redhat.com/application: hello-secret
    appstudio.redhat.com/component: hello-secret
  name: hello-secret
  namespace: ergonzale-tenant
spec:
  image:
    name: hello-secret/hello-secret
    visibility: public
