apiVersion: appstudio.redhat.com/v1beta1
kind: IntegrationTestScenario
metadata:
  labels:
    test.appstudio.openshift.io/optional: "false"
  name: ros-ocp-backend-tekton-insights
  namespace: ergonzale-tenant
spec:
  application: ros-ocp-backend
  params:
  - name: APP_NAME
    value: ros
  - name: COMPONENTS
    value: kruize ros-ocp-backend
  - name: COMPONENTS_W_RESOURCES
    value: ""
  - name: COMPONENT_NAME
    value: ros-ocp-backend
  - name: IQE_PLUGINS
    value: ros_ocp
  - name: IQE_MARKER_EXPRESSION
    value: smoke
  - name: IQE_FILTER_EXPRESSION
    value: ""
  - name: IQE_REQUIREMENTS
    value: ""
  - name: IQE_REQUIREMENTS_PRIORITY
    value: ""
  - name: IQE_TEST_IMPORTANCE
    value: ""
  - name: IQE_CJI_TIMEOUT
    value: 30m
  - name: IQE_ENV
    value: clowder_smoke
  - name: IQE_SELENIUM
    value: "false"
  resolverRef:
    params:
    - name: url
      value: https://github.com/gbenhaim/tekton-insights.git
    - name: revision
      value: main
    - name: pathInRepo
      value: pipelines/basic.yaml
    resolver: git
