apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  annotations:
    build.appstudio.openshift.io/request: configure-pac
    image.redhat.com/generate: '{"visibility": "public"}'
  name: operator
  namespace: tekton-ecosystem-tenant
spec:
  application: openshift-pipelines
  componentName: operator
  source:
    git:
      context: ./
      dockerfileUrl: Dockerfile
      revision: main
      url: https://github.com/openshift-pipelines/operator.git
