apiVersion: appstudio.redhat.com/v1alpha1
kind: ReleasePlan
metadata:
  labels:
    release.appstudio.openshift.io/auto-release: "true"
    release.appstudio.openshift.io/standing-attribution: "true"
  name: sfo-release-as-service
  namespace: sfo-security-tenant
spec:
  application: splunk-forwarder-operator
  target: rhtap-releng-tenant
