---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ReleasePlan
metadata:
  labels:
    release.appstudio.openshift.io/auto-release: 'true'
    release.appstudio.openshift.io/standing-attribution: 'true'
  name: clio-wrklds-pipeline-prod
  namespace: clio-wrklds-pipeline-tenant
spec:
  application: clio-wrklds-pipeline-prod
  target: rhtap-releng-tenant
