---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: release-pvc
  namespace: rh-managed-rh-trex-tenant
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
