apiVersion: appstudio.redhat.com/v1alpha1
kind: ReleasePlan
metadata:
  labels:
    release.appstudio.openshift.io/auto-release: "true"
    release.appstudio.openshift.io/standing-attribution: "true"
  name: release-to-quay-rhtap-ser
  namespace: rhtap-o11y-tenant
spec:
  application: segment-bridge
  displayName: segment-bridge release-to-quay
  target: rh-managed-rhtap-ser-tenant
