apiVersion: appstudio.redhat.com/v1alpha1
kind: ReleasePlan
metadata:
  labels:
    release.appstudio.openshift.io/auto-release: "true"
    release.appstudio.openshift.io/standing-attribution: "true"
  name: workspace-manager-release-to-quay-rhtap-ser
  namespace: rhtap-o11y-tenant
spec:
  application: workspace-manager
  displayName: workspace-manager release-to-quay
  target: rhtap-releng-tenant
