resources:
- release_plan_admission-build.yaml
- release_plan_admission-external-secrets.yaml
- release_plan_admission-internal-services.yaml
- release_plan_admission-release-service.yaml
- release_plan_admission-segment-bridge.yaml
- release-service-account-rb.yaml
- ec-policy.yaml
- release-strategy.yaml
- persistent-volume-claim.yaml
- release-pipeline-sa.yaml
- remote-secrets

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rh-managed-rhtap-ser-tenant
