apiVersion: appstudio.redhat.com/v1alpha1
kind: ReleasePlanAdmission
metadata:
  name: rhtap-internal-services-rpa
  namespace: rh-managed-rhtap-ser-tenant
  labels:
    release.appstudio.openshift.io/auto-release: 'true'
spec:
  application: internal-services
  displayName: ''
  origin: rhtap-release-2-tenant
  releaseStrategy: rhtap-service-push-strategy
