---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ReleasePlanAdmission
metadata:
  name: rhtap-remotesecret-rpa
  namespace: rh-managed-rhtap-ser-tenant
  labels:
    release.appstudio.openshift.io/auto-release: 'true'
spec:
  applications:
    - remotesecret
  data:
    images:
      addGitShaTag: true
      defaultTag: latest
    infra-deployment-update-script: |
      sed -i -e 's|\(https://github.com/redhat-appstudio/remote-secret/config/overlays/openshift_vault?ref=\)\(.*\)|\1{{ revision }}|' components/remote-secret-controller/overlays/development/kustomization.yaml;
      awk  -i inplace -v n=1 '/newTag:/ { if (++count == n) sub(/newTag:.*/, "newTag: {{ revision }}")} 1' components/remote-secret-controller/overlays/development/kustomization.yaml
      sed -i -e 's|\(https://github.com/redhat-appstudio/remote-secret/config/overlays/openshift_aws?ref=\)\(.*\)|\1{{ revision }}|' components/remote-secret-controller/overlays/staging/base/kustomization.yaml;
      sed -i -e 's|\(https://github.com/redhat-appstudio/remote-secret/config/monitoring/prometheus?ref=\)\(.*\)|\1{{ revision }}|' components/remote-secret-controller/overlays/staging/base/kustomization.yaml;
      awk  -i inplace -v n=1 '/newTag:/ { if (++count == n) sub(/newTag:.*/, "newTag: {{ revision }}")} 1' components/remote-secret-controller/overlays/staging/base/kustomization.yaml

    mapping:
      components:
        - name: remotesecret-operator
          repository: "quay.io/redhat-appstudio/remote-secret-controller"
    pyxis:
      secret: pyxis-staging-secret
      server: stage
  origin: rhtap-spi-tenant
  pipelineRef:
    resolver: git
    params:
      - name: url
        value: "https://github.com/redhat-appstudio/release-service-catalog.git"
      - name: revision
        value: main
      - name: pathInRepo
        value: "pipelines/rhtap-service-push/rhtap-service-push.yaml"
  policy: rh-policy
  serviceAccount: rhtap-servicerelease-sa
