---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ReleasePlanAdmission
metadata:
  name: rhtap-release-service-rpa
  namespace: rh-managed-rhtap-ser-tenant
  labels:
    release.appstudio.openshift.io/auto-release: 'true'
spec:
  applications:
    - release-service
  data:
    images:
      addGitShaTag: true
      defaultTag: latest
    infra-deployment-update-script: |
      sed -i -e 's|\(https://github.com/redhat-appstudio/release-service/config/default?ref=\)\(.*\)|\1{{ revision }}|' -e 's/\(newTag: \).*/\1{{ revision }}/' components/release/development/kustomization.yaml
      sed -i -e 's|\(https://github.com/redhat-appstudio/release-service/config/grafana/?ref=\)\(.*\)|\1{{ revision }}|' -e 's//\1{{ revision }}/' components/monitoring/grafana/base/dashboards/release/kustomization.yaml
    mapping:
      components:
        - name: release-service
          repository: "quay.io/redhat-appstudio/release-service"
        - name: release-service-utils
          repository: "quay.io/redhat-appstudio/release-service-utils"
    pyxis:
      secret: pyxis-production-secret
      server: production
    slack:
      slack-notification-secret: "release-team-slack-webhook-notification-secret"
      slack-webhook-notification-secret-keyname: "release"
  origin: rhtap-release-2-tenant
  pipeline:
    pipelineRef:
      resolver: git
      params:
        - name: url
          value: "https://github.com/redhat-appstudio/release-service-catalog.git"
        - name: revision
          value: production
        - name: pathInRepo
          value: "pipelines/rhtap-service-push/rhtap-service-push.yaml"
    serviceAccountName: rhtap-servicerelease-sa
  policy: rh-policy
