apiVersion: appstudio.redhat.com/v1alpha1
kind: ReleasePlanAdmission
metadata:
  name: rhtap-external-secrets-rpa
  namespace: rh-managed-rhtap-ser-tenant
  labels:
    release.appstudio.openshift.io/auto-release: 'true'
spec:
  application: external-secrets
  displayName: ''
  origin: rhtap-gitops-tenant
  releaseStrategy: rhtap-service-push-strategy
