---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ReleaseStrategy
metadata:
  name: push-to-external-registry-strategy
  namespace: rh-managed-rhtap-ser-tenant
spec:
  params:
    - name: extraConfigGitUrl
      value: 'https://github.com/hacbs-release/strategy-configs.git'
    - name: extraConfigPath
      value: rhtap.yaml
    - name: extraConfigRevision
      value: main
    - name: pyxisServerType
      value: stage
    - name: pyxisSecret
      value: pyxis-staging-secret
    - name: tag
      value: latest
    - name: addGitShaTag
      value: 'true'
  pipelineRef:
    resolver: bundles
    params:
    - name: name
      value: push-to-external-registry
    - name: bundle
      value: quay.io/hacbs-release/pipeline-push-to-external-registry:main
    - name: kind
      value: pipeline
  policy: rh-policy
  serviceAccount: rhtap-servicerelease-sa
---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ReleaseStrategy
metadata:
  name: rhtap-service-push-strategy
  namespace: rh-managed-rhtap-ser-tenant
spec:
  params:
    - name: extraConfigGitUrl
      value: 'https://github.com/hacbs-release/strategy-configs.git'
    - name: extraConfigPath
      value: rhtap.yaml
    - name: extraConfigRevision
      value: main
    - name: pyxisServerType
      value: stage
    - name: pyxisSecret
      value: pyxis-staging-secret
    - name: tag
      value: latest
    - name: addGitShaTag
      value: 'true'
  pipelineRef:
    resolver: bundles
    params:
    - name: name
      value: rhtap-service-push
    - name: bundle
      value: quay.io/hacbs-release/pipeline-rhtap-service-push:main
    - name: kind
      value: pipeline
  policy: rh-policy
  serviceAccount: rhtap-servicerelease-sa
