apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  annotations:
    build.appstudio.openshift.io/request: configure-pac
    image.redhat.com/generate: '{"visibility": "public"}'
  name: bug-master-bot-saas-main
  namespace: assisted-installer-tenant
spec:
  application: bug-master-bot-saas-main
  componentName: bug-master-bot-saas-main
  skipGitOpsResourceGeneration: true
  source:
    git:
      context: ./
      dockerfileUrl: Dockerfile
      revision: main
      url: https://github.com/openshift-assisted/bug-master-bot.git
