apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  annotations:
    build.appstudio.openshift.io/request: configure-pac
    image.redhat.com/generate: '{"visibility": "public"}'
  name: assisted-image-service-saas-main
  namespace: assisted-installer-tenant
spec:
  application: assisted-image-service-saas-main
  componentName: assisted-image-service-saas-main
  skipGitOpsResourceGeneration: true
  source:
    git:
      context: ./
      dockerfileUrl: Dockerfile.image-service
      revision: main
      url: https://github.com/openshift/assisted-image-service.git
