apiVersion: appstudio.redhat.com/v1alpha1
kind: ReleasePlan
metadata:
  labels:
    release.appstudio.openshift.io/auto-release: "true"
    release.appstudio.openshift.io/standing-attribution: "true"
  name: prow-jobs-scraper
  namespace: assisted-installer-tenant
spec:
  application: prow-jobs-scraper
  displayName: prow-jobs-scraper
  target: rh-managed-mng-s-2-tenant
