apiVersion: appstudio.redhat.com/v1alpha1
kind: ReleasePlan
metadata:
  labels:
    release.appstudio.openshift.io/author: assisted-installer-team
    release.appstudio.openshift.io/auto-release: "false"
    release.appstudio.openshift.io/releasePlanAdmission: assisted-installer-saas
    release.appstudio.openshift.io/standing-attribution: "false"
  name: assisted-service-saas-hotfix
  namespace: assisted-installer-tenant
spec:
  application: assisted-service-saas-hotfix
  releaseGracePeriodDays: 7
  target: rhtap-releng-tenant
