apiVersion: appstudio.redhat.com/v1alpha1
kind: Application
metadata:
  name: assisted-events-stream-saas-main
  namespace: assisted-installer-tenant
spec:
  displayName: assisted-events-stream-saas-main
