apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - release-plan.yaml
  - maestro.enterprise-contract.integrationtestscenario.yaml
  - maestro/overlay/maestro/main/
  - hypershift-operator-main/
namespace: crt-redhat-acm-tenant
