apiVersion: appstudio.redhat.com/v1beta2
kind: IntegrationTestScenario
metadata:
  name: maestro-main-enterprise-contract
  namespace: crt-redhat-acm-tenant
spec:
  application: maestro-main
  contexts:
  - description: Application testing
    name: application
  params:
  - name: POLICY_CONFIGURATION
    value: rhtap-releng-tenant/app-interface-standard
  resolverRef:
    params:
    - name: url
      value: https://github.com/konflux-ci/build-definitions
    - name: revision
      value: main
    - name: pathInRepo
      value: pipelines/enterprise-contract.yaml
    resolver: git
