kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
# Naming: <API_GROUP>/<KIND_PLURAL>/<METADATA_NAME>
resources:
  - appstudio.redhat.com/integrationtestscenarios/multiarch-tuning-operator-enterprise-contract
  - appstudio.redhat.com/releaseplans/multiarch-tuning-operator-release-as-operator

