apiVersion: appstudio.redhat.com/v1beta1
kind: IntegrationTestScenario
metadata:
  labels:
    test.appstudio.openshift.io/optional: "false" # Change to "true" if you don't need the test to be mandatory
  name: ingress-tekton-insights 
  namespace: rh-devprod-tenant
spec:
  application: ingress
  resolverRef:
    params:
    - name: url
      value: https://github.com/gbenhaim/tekton-insights.git # Temporary on gbenhaim's org. Also, you can fork it and reference yours here.
    - name: revision
      value: main # Or whatever branch you want to test
    - name: pathInRepo
      value: pipelines/basic.yaml # This is the path to the pipeline
    resolver: git
  params:
    - name: APP_NAME
      value: ingress
    - name: COMPONENTS
      value: ingress
    # - name: COMPONENTS_W_RESOURCES
    #   value: # List of components to keep.
    - name: COMPONENT_NAME #IMPORTANT: Your component in RHTAP has to be named the same as this field.
      value: ingress
    - name: IQE_PLUGINS
      value: ingress
    - name: IQE_MARKER_EXPRESSION
      value: smoke
    # - name: IQE_FILTER_EXPRESSION
    #   value: # This is the value passed to pytest -k. Default is "" when no filter desired
    # - name: IQE_REQUIREMENTS
    #   value: # "something,something_else" -- iqe requirements filter. Default is "" when no filter desired
    # - name: IQE_REQUIREMENTS_PRIORITY
    #   value: # "something,something_else" -- iqe requirements priority filter. Default is "" when no filter desired
    # - name: IQE_TEST_IMPORTANCE
    #   value: # "something,something_else" -- iqe test importance filter. Default is "" when no filter desired
    - name: IQE_CJI_TIMEOUT
      value: 30m
    # - name: IQE_ENV
    #   value: # "something" -- value to set for ENV_FOR_DYNACONF. Default is "clowder_smoke"
    # - name: IQE_SELENIUM
    #   value: # Whether to run IQE pod with a selenium container. Default is "false"
