apiVersion: appstudio.redhat.com/v1alpha1
kind: ReleasePlanAdmission
metadata:
  labels:
    release.appstudio.openshift.io/auto-release: "true"
  name: centos-bootc-c10s
  namespace: rh-managed-bifrost-tenant
spec:
  applications:
  - centos-bootc-c10s
  data:
    mapping:
      components:
      - name: centos-bootc-c10s
        pushSourceContainer: false
        repository: quay.io/centos-bootc/centos-bootc
        tags:
        - stream10
        - c10s
  origin: centos-bootc-tenant
  pipeline:
    pipelineRef:
      params:
      - name: url
        value: https://github.com/konflux-ci/release-service-catalog.git
      - name: revision
        value: production
      - name: pathInRepo
        value: pipelines/push-to-external-registry/push-to-external-registry.yaml
      resolver: git
    serviceAccountName: release-sa-centos-bootc
  policy: rh-policy
