apiVersion: appstudio.redhat.com/v1beta1
kind: RemoteSecret
metadata:
  name: centos-bootc-tenant-quay-token-secret-remote-secret
  namespace: rh-managed-bifrost-tenant
spec:
  secret:
    linkedTo:
    - serviceAccount:
        reference:
          name: release-sa-centos-bootc
    name: centos-bootc-tenant-quay-token-secret
    type: kubernetes.io/dockerconfigjson
  targets:
  - namespace: rh-managed-bifrost-tenant
