apiVersion: appstudio.redhat.com/v1beta1
kind: RemoteSecret
metadata:
  name: redhat-user-workloads-pull
  namespace: rh-managed-bifrost-tenant
spec:
  secret:
    linkedTo:
    - serviceAccount:
        reference:
          name: release-sa-centos-bootc
    name: redhat-user-workloads-pull
    type: kubernetes.io/dockerconfigjson
  targets:
  - namespace: rh-managed-bifrost-tenant
