apiVersion: appstudio.redhat.com/v1alpha1
kind: ReleasePlanAdmission
metadata:
  labels:
    release.appstudio.openshift.io/auto-release: "true"
  name: fedora-bootc
  namespace: rh-managed-bifrost-tenant
spec:
  applications:
  - fedora-bootc
  data:
    images:
      addGitShaTag: true
      floatingTags:
      - eln
    mapping:
      components:
      - name: fedora-bootc
        repository: quay.io/centos-bootc/fedora-bootc
  origin: centos-bootc-tenant
  pipeline:
    pipelineRef:
      params:
      - name: url
        value: https://github.com/konflux-ci/release-service-catalog.git
      - name: revision
        value: production
      - name: pathInRepo
        value: pipelines/push-to-external-registry/push-to-external-registry.yaml
      resolver: git
    serviceAccountName: release-sa-centos-bootc
  policy: rh-policy
