apiVersion: appstudio.redhat.com/v1beta1
kind: IntegrationTestScenario
metadata:
  labels:
    test.appstudio.openshift.io/optional: "false"
  name: insights-content-template-renderer-tekton-insights
  namespace: rh-ccx-tenant
spec:
  application: insights-content-template-renderer
  params:
  - name: APP_NAME
    value: ccx-data-pipeline
  - name: COMPONENTS
    value: insights-content-template-renderer
  - name: COMPONENTS_W_RESOURCES
    value: insights-content-template-renderer
  - name: COMPONENT_NAME
    value: insights-content-template-renderer
  - name: IQE_PLUGINS
    value: ccx
  - name: IQE_MARKER_EXPRESSION
    value: null
  - name: IQE_FILTER_EXPRESSION
    value: test_plugin_accessible
  - name: IQE_CJI_TIMEOUT
    value: 30m
  resolverRef:
    params:
    - name: url
      value: https://github.com/RedHatInsights/bonfire-tekton.git
    - name: revision
      value: main
    - name: pathInRepo
      value: pipelines/basic.yaml
    resolver: git
