apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rh-managed-bifrost-tenant-release-service-pipeline-rolebinding-managed
  namespace: rh-managed-bifrost-tenant
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: release-pipeline-resource-role
subjects:
  - kind: ServiceAccount
    name: release-sa-centos-bootc
    namespace: rh-managed-bifrost-tenant
