apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  annotations:
    appstudio.openshift.io/pac-provision: request
    build.appstudio.openshift.io/request: configure-pac
    image.redhat.com/generate: "true"
  name: siteconfig-main
  namespace: crt-redhat-acm-tenant
spec:
  application: siteconfig-main
  componentName: siteconfig
  source:
    git:
      context: ./
      dockerfileUrl: Dockerfile
      revision: main
      url: https://github.com/stolostron/siteconfig
  targetPort: 8080
