apiVersion: appstudio.redhat.com/v1alpha1
kind: ReleasePlan
metadata:
  labels:
    release.appstudio.openshift.io/auto-release: "true"
    release.appstudio.openshift.io/standing-attribution: "true"
  name: maestro
  namespace: crt-redhat-acm-tenant
spec:
  application: maestro-main
  target: rhtap-releng-tenant
