apiVersion: appstudio.redhat.com/v1alpha1
kind: ReleasePlanAdmission
metadata:
  name: fbc-staged-index-release-v4-14
  namespace: rh-managed-cnv-fbc-tenant
spec:
  application: cnv-fbc-v4-14
  origin: cnv-fbc-tenant
  releaseStrategy: fbc-staged-index-strategy
