apiVersion: appstudio.redhat.com/v1beta1
kind: RemoteSecret
metadata:
  name: fbc-publishing-credentials-remote-secret
  namespace: rh-managed-cnv-fbc-tenant
spec:
  secret:
    linkedTo:
    - serviceAccount:
        reference:
          name: release-service-account
    name: fbc-publishing-credentials
    type: Opaque
  targets:
  - namespace: rh-managed-cnv-fbc-tenant
