apiVersion: appstudio.redhat.com/v1alpha1
kind: ReleasePlanAdmission
metadata:
  name: fbc-staged-index-release
  namespace: rh-managed-cnv-fbc-tenant
spec:
  application: cnv-fbc
  origin: cnv-fbc-tenant
  releaseStrategy: fbc-staged-index-strategy
