apiVersion: appstudio.redhat.com/v1alpha1
kind: EnterpriseContractPolicy
metadata:
  name: rh-fbc-stage-index-policy
  namespace: rh-managed-cnv-fbc-tenant
spec:
  configuration:
    exclude:
    - cve
    - step_image_registries
    - test.required_tests_passed:fbc-related-image-check
    - tasks.pipeline_has_tasks:prefetch-dependencies
    include:
    - '@redhat'
  description: Includes rules for shipping Red Hat FBC fragments without tests
  publicKey: k8s://openshift-pipelines/public-key
  sources:
  - data:
    - github.com/enterprise-contract/ec-policies//data
    name: Default
    policy:
    - github.com/enterprise-contract/ec-policies//policy/lib
    - github.com/enterprise-contract/ec-policies//policy/release
