apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cnv-fbc-tenant-release-service-pipeline-rolebinding-dev
  namespace: rh-managed-cnv-fbc-tenant
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: release-pipeline-resource-role
subjects:
- kind: ServiceAccount
  name: release-service-account
  namespace: rh-managed-cnv-fbc-tenant
