apiVersion: appstudio.redhat.com/v1beta1
kind: IntegrationTestScenario
metadata:
  labels:
    test.appstudio.openshift.io/optional: "false"
  name: pulp-bonfire-tekton
  namespace: pulp-services-tenant
spec:
  application: pulp
  params:
  - name: APP_NAME
    value: pulp
  - name: COMPONENTS
    value: null
  - name: COMPONENTS_W_RESOURCES
    value: pulp
  - name: BONFIRE_COMPONENT_NAME
    value: null
  - name: COMPONENT_NAME
    value: pulp
  - name: EXTRA_DEPLOY_ARGS
    value: --set-parameter pulp/PULP_API_MEMORY_LIMIT=4096Mi --set-parameter pulp/PULP_API_MEMORY_REQUEST=2048Mi
      provisioning sources image-builder-crc
  resolverRef:
    params:
    - name: url
      value: https://github.com/pulp/pulp-service.git
    - name: revision
      value: main
    - name: pathInRepo
      value: .tekton/pulp-deploy-and-test.yaml
    resolver: git
