apiVersion: appstudio.redhat.com/v1beta1
kind: RemoteSecret
metadata:
  name: pyxis-staging-secret-remote-secret
spec:
  secret:
    name: pyxis-staging-secret
    type: Opaque
    linkedTo:
      - serviceAccount:
          reference:
            name: release-service-account
  targets:
    - namespace: rh-managed-mng-s-2-tenant 
---
apiVersion: appstudio.redhat.com/v1beta1
kind: RemoteSecret
metadata:
  name: pyxis-production-secret-remote-secret
spec:
  secret:
    name: pyxis-production-secret
    type: Opaque
    linkedTo:
      - serviceAccount:
          reference:
            name: release-service-account
  targets:
    - namespace: rh-managed-mng-s-2-tenant 
