apiVersion: appstudio.redhat.com/v1beta2
kind: IntegrationTestScenario
metadata:
  name: cloud-image-directory-enterprise-contract
  namespace: cid-cloudx-tenant
spec:
  params:
    - name: POLICY_CONFIGURATION
      value: rhtap-releng-tenant/tmp-onboard-policy
  application: cloud-image-directory
  contexts:
    - description: Application testing
      name: application
  resolverRef:
    params:
      - name: url
        value: 'https://github.com/redhat-appstudio/build-definitions'
      - name: revision
        value: main
      - name: pathInRepo
        value: pipelines/enterprise-contract.yaml
    resolver: git