apiVersion: appstudio.redhat.com/v1alpha1
kind: ReleasePlanAdmission
metadata:
  name: bonfire-cicd-tools
  namespace: rh-managed-mng-s-2-tenant
spec:
  applications:
  - bonfire-cicd-tools
  data:
    images:
      addGitShaTag: true
      defaultTag: latest
    mapping:
      components:
      - name: cicd-tools
        repository: quay.io/rhtap-managed-services/rhtap-migration-bonfire-cicd-tools
    pyxis:
      secret: pyxis-production-secret
      server: production
  origin: rhtap-migration-tenant
  pipelineRef:
    params:
    - name: url
      value: https://github.com/redhat-appstudio/release-service-catalog.git
    - name: revision
      value: main
    - name: pathInRepo
      value: pipelines/push-to-external-registry/push-to-external-registry.yaml
    resolver: git
  policy: app-interface-standard
  serviceAccount: release-service-account
