apiVersion: appstudio.redhat.com/v1beta1
kind: RemoteSecret
metadata:
  name: rh-trex-tenant-quay-token-secret-remote-secret
  namespace: rh-managed-mng-s-2-tenant
spec:
  secret:
    linkedTo:
    - serviceAccount:
        reference:
          name: rh-trex-tenant-release-service-account
    name: rh-trex-tenant-quay-token-secret
    type: kubernetes.io/dockerconfigjson
  targets:
  - namespace: rh-managed-mng-s-2-tenant
