apiVersion: appstudio.redhat.com/v1alpha1
kind: ReleaseStrategy
metadata:
  name: push-to-external-registry-strategy
  namespace: rh-managed-mng-s-2-tenant
spec:
  params:
  - name: extraConfigGitUrl
    value: https://github.com/hacbs-release/strategy-configs.git
  - name: extraConfigPath
    value: mng-s-2.yaml
  - name: extraConfigRevision
    value: main
  - name: pyxisServerType
    value: stage
  - name: pyxisSecret
    value: pyxis
  - name: tag
    value: latest
  - name: addGitShaTag
    value: "true"
  pipelineRef:
    params:
    - name: name
      value: push-to-external-registry
    - name: bundle
      value: quay.io/hacbs-release/pipeline-push-to-external-registry:main
    - name: kind
      value: pipeline
    resolver: bundles
  policy: rh-policy
  serviceAccount: release-service-account
