apiVersion: appstudio.redhat.com/v1alpha1
kind: ReleasePlanAdmission
metadata:
  name: terraform-provider-rhcs-rhtap
  namespace: rh-managed-mng-s-2-tenant
spec:
  applications:
  - terraform-provider-rhcs-rhtap
  data:
    github:
      githubSecret: github-secret
  origin: rh-terraform-tenant
  pipelineRef:
    params:
    - name: url
      value: https://github.com/ernesgonzalez33/release-service-catalog.git
    - name: revision
      value: add-terraform-pipeline
    - name: pathInRepo
      value: pipelines/release-to-github-signed/release-to-github-signed.yaml
    resolver: git
  policy: rh-policy
  serviceAccount: release-service-account
