apiVersion: appstudio.redhat.com/v1alpha1
kind: ReleasePlan
metadata:
  labels:
    release.appstudio.openshift.io/auto-release: "true"
    release.appstudio.openshift.io/standing-attribution: "true"
  name: release-service-release-to-quay-rhtap-ser
  namespace: rhtap-release-2-tenant
spec:
  application: release-service
  displayName: release-service release-to-quay
  target: rh-managed-rhtap-ser-tenant
