apiVersion: appstudio.redhat.com/v1alpha1
kind: ReleasePlan
metadata:
  labels:
    release.appstudio.openshift.io/auto-release: "true"
    release.appstudio.openshift.io/standing-attribution: "true"
  name: multi-platform-controller-otp-service-release-to-quay-rhtap-ser
  namespace: rhtap-build-tenant
spec:
  application: multi-platform-controller
  target: rhtap-releng-tenant
