apiVersion: appstudio.redhat.com/v1alpha1
kind: ReleasePlan
metadata:
  labels:
    release.appstudio.openshift.io/auto-release: "true"
    release.appstudio.openshift.io/standing-attribution: "true"
  name: source-container-build-release-to-quay-rhtap-ser
  namespace: rhtap-build-tenant
spec:
  application: build-tasks-dockerfiles
  target: rhtap-releng-tenant
