apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "-1"
  name: registry-redhat-io-pull-secret
  namespace: rhtap-build-tenant
spec:
  dataFrom:
  - extract:
      key: production/build/rh-syft/registry-pull-secret
  refreshInterval: 15m
  secretStoreRef:
    kind: ClusterSecretStore
    name: appsre-stonesoup-vault
  target:
    creationPolicy: Owner
    deletionPolicy: Delete
    name: registry-redhat-io-pull-secret
    template:
      data:
        .dockerconfigjson: '{{ .config }}'
      engineVersion: v2
      type: kubernetes.io/dockerconfigjson
