apiVersion: v1
imagePullSecrets:
- name: registry-redhat-io-pull-secret
kind: ServiceAccount
metadata:
  name: appstudio-pipeline
  namespace: rhtap-build-tenant
secrets:
- name: registry-redhat-io-pull-secret
