apiVersion: appstudio.redhat.com/v1beta1
kind: RemoteSecret
metadata:
  name: github-pat-terraform-redhat-terraform-provider-rhcs-remote-secret
  namespace: rhtap-releng-tenant
spec:
  secret:
    linkedTo:
    - serviceAccount:
        reference:
          name: release-github-terraform-prod
    name: github-pat-terraform-redhat-terraform-provider-rhcs-secret
    type: Opaque
  targets:
  - namespace: rhtap-releng-tenant
