apiVersion: appstudio.redhat.com/v1beta1
kind: RemoteSecret
metadata:
  name: quay-token-redhat-services-staging-secret-remote-secret
  namespace: rhtap-releng-tenant
spec:
  secret:
    linkedTo:
    - serviceAccount:
        reference:
          name: release-app-interface-staging
    name: quay-token-redhat-services-staging-secret
    type: kubernetes.io/dockerconfigjson
  targets:
  - namespace: rhtap-releng-tenant
