apiVersion: appstudio.redhat.com/v1beta1
kind: RemoteSecret
metadata:
  name: quay-token-konflux-ci-secret-remote-secret
  namespace: rhtap-releng-tenant
spec:
  secret:
    linkedTo:
    - serviceAccount:
        reference:
          name: konflux-ci-servicerelease-sa
    name: quay-token-konflux-ci-secret
    type: kubernetes.io/dockerconfigjson
  targets:
  - namespace: rhtap-releng-tenant
