apiVersion: appstudio.redhat.com/v1beta1
kind: RemoteSecret
metadata:
  name: quay-token-redhat-acs-remote-secret
  namespace: rhtap-releng-tenant
spec:
  secret:
    linkedTo:
    - serviceAccount:
        reference:
          name: redhat-acs-service-account
    name: quay-token-redhat-acs-secret
    type: kubernetes.io/dockerconfigjson
  targets:
  - namespace: rhtap-releng-tenant
