apiVersion: appstudio.redhat.com/v1beta1
kind: RemoteSecret
metadata:
  name: pyxis-staging-secret-remote-secret
  namespace: rhtap-releng-tenant
spec:
  secret:
    linkedTo:
    - serviceAccount:
        reference:
          name: release-service-account
    name: pyxis-staging-secret
    type: Opaque
  targets:
  - namespace: rhtap-releng-tenant
