---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ReleasePlanAdmission
metadata:
  name: bootc-image-builder
  namespace: rh-managed-bifrost-tenant
  labels:
    release.appstudio.openshift.io/auto-release: 'true'
spec:
  applications:
    - bootc-image-builder
  data:
    images:
      addGitShaTag: true
      floatingTag: "latest"
    mapping:
      components:
        - name: bootc-image-builder
          repository: "quay.io/centos-bootc/bootc-image-builder"
  origin: centos-bootc-tenant
  pipelineRef:
    resolver: git
    params:
      - name: url
        value: "https://github.com/redhat-appstudio/release-service-catalog.git"
      - name: revision
        value: production
      - name: pathInRepo
        value: "pipelines/push-to-external-registry/push-to-external-registry.yaml"
  policy: rh-policy
  serviceAccount: release-sa-centos-bootc
