---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ReleasePlanAdmission
metadata:
  name: centos-bootc
  namespace: rh-managed-bifrost-tenant
  labels:
    release.appstudio.openshift.io/auto-release: 'true'
spec:
  applications:
    - centos-bootc
  data:
    images:
      addGitShaTag: true
      floatingTags:
        - stream9
    mapping:
      components:
        - name: centos-bootc
          repository: "quay.io/centos-bootc/centos-bootc"
  origin: centos-bootc-tenant
  pipelineRef:
    resolver: git
    params:
      - name: url
        value: "https://github.com/redhat-appstudio/release-service-catalog.git"
      - name: revision
        value: production
      - name: pathInRepo
        value: "pipelines/push-to-external-registry/push-to-external-registry.yaml"
  policy: rh-policy
  serviceAccount: release-sa-centos-bootc
