apiVersion: appstudio.redhat.com/v1alpha1
kind: ReleasePlan
metadata:
  labels:
    release.appstudio.openshift.io/auto-release: "true"
    release.appstudio.openshift.io/standing-attribution: "true"
  name: helm-operator
  namespace: orchestrator-releng-tenant
spec:
  application: helm-operator
  target: rhtap-releng-tenant
