apiVersion: appstudio.redhat.com/v1alpha1
kind: ReleasePlan
metadata:
  labels:
    release.appstudio.openshift.io/auto-release: "true"
    release.appstudio.openshift.io/standing-attribution: "true"
  name: orchestrator-helm-operator
  namespace: orchestrator-releng-tenant
spec:
  application: orchestrator-helm-operator
  target: orchestrator-releng-tenant
