apiVersion: appstudio.redhat.com/v1alpha1
kind: ReleasePlan
metadata:
  labels:
    release.appstudio.openshift.io/auto-release: "true"
    release.appstudio.openshift.io/standing-attribution: "true"
  name: git-clone-release-to-quay-konflux-ser
  namespace: konflux-build-pipeli-tenant
spec:
  application: git-clone
  target: rhtap-releng-tenant
