apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  annotations:
    build.appstudio.openshift.io/request: configure-pac
    image.redhat.com/generate: '{"visibility": "public"}'
  name: git-clone
  namespace: konflux-build-pipeli-tenant
spec:
  application: git-clone
  componentName: git-clone
  source:
    git:
      context: ./
      dockerfileUrl: Dockerfile
      revision: main
      url: https://github.com/konflux-ci/git-clone.git
